---
title: "Learn Web"
author: "ale66"
format: 
  revealjs:
    footer: "[github.com/ale66/learn-web](https://github.com/ale66/learn-web)&nbsp;&nbsp;&nbsp;"
    theme: [solarized]
    preview-links: auto
    chalkboard: 
      boardmarker-width: 5
    mermaid:
      theme: forest
      fontSize: 12
from: markdown+emoji
execute:
  echo: true
---

# Structure


---

## Important properties

Whereas rendered pages are normally related to a linear, left-to-right, top-down reading, browsers see pages as *trees*

Biological tree: one *root* element at the bottom which splits up repeatedly in smaller and smaller branches; leaves at the top


---

HTML tree: flipped upside down

a single root element at the top

branching out into several smaller elements, some of which are siblings


---

## Parsing

Automated reading of a formal (code) file with *recognition* of the commands

HTML branch tags must be strictly contained into their *root*

are mistyping can throw the automated parsing off track


---


```html
<!doctype html>
```

This is not strictly HTML and it is read by the OS under the browser

---

```html
<!doctype html>

<html lang="en">
</html>
```

---

One root, two branches

```html
<!doctype html>

<html>
  <head></head>
  <body></body>
</html>
```

This part is mandatory

```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
```

---

```html
<!doctype html>

<html>
  <head>
    <title>My DOM page</title>
  </head>
  <body>
    <h1>Visible title</h1>
    <p>Text</p>
  </body>
</html>
```

One root, two branches and two leaves

```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p]
```


---

```html
<html>
  <head>
    <title>My DOM page</title>
  </head>
  <body>
    <h1>Visible title</h1>
    <p>Some text</p>
    <p>More text</p>
    <p>Further text</p>
...
```

```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p] & G[p] & H[p]
```


---

Browsers process tags as *paths* from root to leaf:

```html
<html><head><h1>Visible title</h1>
```

```html
<html><head><p>Some text</p>
```

Each leaf will be uniquely identified

Next, all the needed CSS command will be picked up from the CSS file and attached to the element

```html
<html><head><h1 class="my-hero-title">Title</h1>
```

```css
.my-hero-title {
  font-color: darksalmon;
  ...
}
```

Free choice of class names but they must be unique


---

## How browers actually see our page 


```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p] & G[p] & H[p]
  E-.-> I[.my-hero-title]
```




# The DOM 


---

## Document Object model

each HTML page has an associated *tree* representation with tags and class names

the tree representation guides the writing of JavaScript (JS) programs that can manipulate the structure of the page 

and how it looks to, e.g., classes of users

__We study the DOM to manipulate pages__


---

## Exercise: view the DOM of your own exercise

Take your own HTML project for MA COM

[DOM Visualiser from GitHub](https://codu-code.github.io/dom-visualizer/index.html)

[Another one](http://bioub.github.io/dom-visualizer/)

---

## Represent content


```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p] & G[p] & H[p]
  E-.-> I[.my-hero-title]
```

inside most tags there is content to be displayed.

Such content is represented as an explicit leaf of our DOM


---

##

```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p] & G[p] & H[p]
  E-.-> I[.my-hero-title]
  D --> L[My DOM page]
  E --> M[My visible title]
  F --> N[some text]
  G --> O[more text]
  H --> P[further text]
```

for each leaf, a special ``innerHTML`` variable will contain the relative text and mark-up


---

The complete DOM

```{mermaid}
%%| echo: false
flowchart LR
  A[html] --> B[head] & C[body]
  B --> D[title]
  C --> E[h1] & F[p] & G[p] & H[p]
  E-.-> I[.my-hero-title]
  D --> L[My DOM page]
  E --> M[My visible title]
  F --> N[some text]
  F-.-> Q[.my-p-style]
  G --> O[more text]
  G-.-> Q
  H --> P[further text]
  H-.-> Q
```
