---
title: "Web Communication 2026-27"
subtitle: 'v. of Sep. 15th'
author: ''
date: ''
format:
  html:
    toc: false
    toc-depth: 2
    number-sections: true
---

This course introduces students to the principles and practice of web
communication and web design, from basic HTML/CSS to JavaScript, responsive layout, and beyond. 
All lecture materials, exercises, and boilerplate code
are published in the course GitHub repository. 
Please register for a [github.com/](https://github.com/) account using your *@studenti.unimi.it* account and join [https://github.com/education](https://github.com/education).


## Online Course resources 

| Resource | Link |
|---|---|
| Moodle (course page, quizzes, readings) | [myariel.unimi.it/course/view.php?id=12470](https://myariel.unimi.it/course/view.php?id=12470) |
| MS Teams (live sessions, announcements, chat) | [MS Teams team](https://teams.microsoft.com/l/team/19%3A9LnhbtG9QgJM2nTxbl_EV1XOVHQ-Pds5TiH_Y52sDDI1%40thread.tacv2/conversations?groupId=a1903621-5288-463d-baf7-5ffc799cd4f6&tenantId=13b55eef-7018-4674-a3d7-cc0db06d545c) |
| GitHub (lecture materials & code) | [github.com/ale66/learn-web](https://github.com/ale66/learn-web) |
 Web design playground (learn HTML+CSS online) | [wdpg.io/](https://www.webdesignplayground.io/) | 


## Logistics

Lectures take place in *Laboratorio 2* on the ground floor of the *Passione* building. 
Lectures run 14:30--17:30 on Friday and 9:00--11:45 on Saturday. 
A (low-fi) AV broadcast and lecture recording will be available.


## Contacts

Questions on course materials, coding etc.: please post on Teams so all benefit from the answer.

Questions on personal project/studies: you may contact me on Teams anytime.

In-person office hours: Friday after class and Saturday before class.


## Calendar

| Week | Friday | Saturday |
|-|------|------|
| 0 | Onboarding | HTML as Typography |
|   | Os, WDPG | Lorem Ipsum Boilerplate |
| 1 | Formal languages |    |
|   | Version control |  |  
| 2 | HTTP | The DOM   |
|   | Structural Tags | AV, linking |  
| 3 | Frames | External CSSs   |
|   | MD, Pandoc | Liquid |  
| 4 | Page Layouts | CSSs  |
|   | Landing Pages | JS-1 |  
| 5 | Responsive Design | Mid-term project |
|   | Flexbox |  |  
| 6 |  Media queries  | Bootstrap |
|   |  |  |  
| 7 | Cookies | POST methods  |
|   | | RevealJS lab Carousels |  
| 8 | A/B Testing  | post methods |
|   | Web privacy  | Carousels |  
| 9 | SEO | Project reviews |
|   | Meta tags  |  |  



## Software Tools

Installed these to follow the course and complete exercises:

- **Web browser** Firefox will be used in class. 

- **Package manager** to quickly install/update software. For Win: install [chocolatey.org](https://chocolatey.org/); For Mac: install [brew.sh](https://brew.sh/).

- **Code editor** [code.visualstudio.com/](https://code.visualstudio.com/); also available online at [vscode.dev/](https://vscode.dev/).
- **document converter** from [pandoc.org/](https://pandoc.org/), used under the hood by Quarto; also available online at [pandoc.org/try/](https://pandoc.org/try/).
- **Renderer** [quarto.org/](https://quarto.org/) for authoring and rendering course materials (HTML, PDF, RevealJS slides)
- **Version control software** [git-scm.com/](https://git-scm.com/).
- **A modern Git manager**, e.g., [fork.dev](https://fork.dev/). 

## Exams

Prepare a Web Communication project consisting of a *pitch deck* for a technical audience, a stub web page with styles, AV contents, links etc parked on your GitHub space and coordinated with email campaign plans and social media presence (IG, FB, X, WA etc.). 
The oral exam consists of presenting the technical side of your project and showing *ownership* of the code.

**Exam dates** December 18 and 19 in person at the *sala seminari* on the second floor of the *Passione* building (TBC). 
Exam slots are bookable via Teams. Arrangements are available for Erasmus/exchange students who need to leave Milan earlier.
For 2027, January 13 and 14 (TBC) and dates in March and July. 


