<!-- Webcomm boilerplate for a page with visitor interaction
    please do not edit this file

    This is the 'root' file of the project
-->

<html>
  <head>
    <link href= "index.html">
    <link rel="icon" href="imgs/logo.jpg" type="image/png">
    <title></title>
  </head>
  
  <body>
    <!-- Connect index.php with index-html -->
    <?php include 'index.html';?>
  </body>
</html>
